### ISSUE TITLE
The right answer to the merge drill is treatead like the wrong one

### ISSUE THREAD

**Issue by dskecse** [bobbyno/ruby_drills#16]
It seems like comparison of an `input` and a `reference` is done the wrong way, since comparing hashes - unordered collections - as strings simply won't work as expected.
Consider the reference solution from the `merge` drill:

    "@matched_animals.merge(@mismatched_animals) { |key, v1, v2| v1 }"

Passed through to `Pry.run_command`, it produces the following result:

    "=> {\"cat\"=>\"meow\", \"dog\"=>\"woof\", \"frog\"=>\"ribbit\", \"pig\"=>\"oink\"}"

My proposed solution

    "@mismatched_animals.merge(@matched_animals)"

gives the following result:

    "=> {\"cat\"=>\"meow\", \"dog\"=>\"woof\", \"pig\"=>\"oink\", \"frog\"=>\"ribbit\"}"

Hence comparison of the two strings results in `false`.

**Comment by dskecse** [comment]
Here's the PR that resolves the issue: https://github.com/bobbyno/ruby_drills/pull/17.

**Comment by saslani** [comment]
Thank you!
